package checks

// commandNames is gCommands (War3D/commands.cpp:30), the whole set of commands
// the engine can build. A battle script naming anything else builds no command
// at all, so its event fires and does nothing.
//
// Taken from the table as it stands. A command added to the engine without
// being added here reads as unknown, which is the safe direction to be wrong
// in only if this stays in step -- check it when the engine's table changes.
var commandNames = map[string]bool{
	"aboutface": true, "addcommqueue": true, "addcourtxt": true, "addpoints": true,
	"addwaypoint": true, "advance": true, "altform": true, "altstart": true,
	"applyoptions": true, "artyfireai": true, "artyfirearty": true, "artyfirecavalry": true,
	"artyfirehold": true, "artyfiretroops": true, "attach": true, "attackmarch": true,
	"begcampaign": true, "begrandom": true, "benchmark": true, "camfollow": true,
	"casualty": true, "charge": true, "chat": true, "clearcourmsg": true,
	"clearwaypoints": true, "close": true, "closebar": true, "closelevel": true,
	"closenomusic": true, "courdoc": true, "courier": true, "deactivate": true,
	"defaultoptions": true, "delcampaign": true, "delcommqueue": true, "delevt": true,
	"delreplay": true, "delsave": true, "detach": true, "doneloc": true,
	"donequad": true, "donevp": true, "dumpdead": true, "dumpgamedb": true,
	"dumplocs": true, "dumpoobscen": true, "dumpscen": true, "dumpunused": true,
	"enddir": true, "endscenario": true, "exit": true, "fallback": true,
	"fightform": true, "fillmpserver": true, "fire": true, "flushcommqueue": true,
	"flushvars": true, "follow": true, "follownone": true, "forcemove": true,
	"forcepath": true, "form": true, "formtype": true, "gathercarry": true,
	"gatherhigh": true, "getaway": true, "goto": true, "gotosel": true,
	"gotounit": true, "guard": true, "guardsel": true, "help": true,
	"hideunit": true, "highground": true, "highscore": true, "immortal": true,
	"joinbrig": true, "joinbrigsel": true, "justrun": true, "killoff": true,
	"limber": true, "loadbar": true, "loadbarcour": true, "loadcampaign": true,
	"loadcour": true, "loadgame": true, "loadlayout": true, "loadlevel": true,
	"loadmenu": true, "loadoptions": true, "loadreplay": true, "loadscen": true,
	"loadscreen": true, "loadspec": true, "loadwl": true, "lobbycreateroom": true,
	"lobbyenterpass": true, "lobbyenterroom": true, "lobbyfree": true, "lobbylaunch": true,
	"lobbyleaveroom": true, "lobbylogon": true, "lobbyrefresh": true, "lobbysendroom": true,
	"lockunit": true, "logmsg": true, "mapport": true, "marchmusic": true,
	"mleftflank": true, "mleftoblique": true, "mortal": true, "movebackward": true,
	"movedir": true, "movedown": true, "moveformfwd": true, "moveforward": true,
	"movefwd": true, "moveleft": true, "movemoddn": true, "movemodup": true,
	"movepath": true, "moveright": true, "movespec": true, "moveto": true,
	"moveup": true, "mpsandbox": true, "mrightflank": true, "mrightoblique": true,
	"msgbox": true, "multicourmsg": true, "multifree": true, "multihost": true,
	"multijoin": true, "multikick": true, "multilaunch": true, "multiload": true,
	"multisendchat": true, "multisetofficer": true, "multisetscen": true, "mycourier": true,
	"newsel": true, "night": true, "notused": true, "notused2": true,
	"objactivate": true, "onlydismount": true, "onlylaydown": true, "onlylimber": true,
	"onlymount": true, "onlyriseup": true, "onlyunlimber": true, "orderdest": true,
	"orders": true, "parsecmd": true, "pause": true, "playatloc": true,
	"playmp3": true, "plyrdest": true, "popcourmsg": true, "poplayout": true,
	"popscreen": true, "quickload": true, "quicksel": true, "raid": true,
	"rally": true, "ranevt": true, "rankdown": true, "ranknext": true,
	"rankprev": true, "rankup": true, "ranrandom": true, "replay_frame": true,
	"replay_play": true, "resign": true, "resupply": true, "retreat": true,
	"roadmarch": true, "rotateleft": true, "rotateright": true, "route": true,
	"run": true, "safeplace": true, "savecampaign": true, "savegame": true,
	"savemods": true, "savereplay": true, "sbcattach": true, "sbcbattle": true,
	"sbcdetach": true, "sbcfastplay": true, "sbcfight": true, "sbcpause": true,
	"sbcplay": true, "sbcretreat": true, "sbcsave": true, "sbcsetdest": true,
	"sbctrain": true, "scout": true, "screen": true, "sendcommqueue": true,
	"sendcourmsg": true, "setammo": true, "setcourvars": true, "setfov": true,
	"setgroup": true, "setleaders": true, "setvar": true, "setvars": true,
	"showmenu": true, "showunit": true, "speeddown": true, "speedup": true,
	"split": true, "splitbrig": true, "state": true, "stop": true,
	"stopmp3": true, "stopsfx": true, "sunrise": true, "sunset": true,
	"surrender": true, "switchcmn": true, "tachold": true, "tacloc": true,
	"tacorders": true, "tacquad": true, "tacquadloc": true, "tacquadvp": true,
	"tacreserve": true, "tactics": true, "tacvp": true, "takecommand": true,
	"takecover": true, "target": true, "targetsel": true, "tcalloff": true,
	"tcallon": true, "tcofficers": true, "tcommoff": true, "tcommon": true,
	"teamchat": true, "toggleflags": true, "togglehud": true, "toggletrees": true,
	"unitsonly": true, "unlockunit": true, "unsplit": true, "unused": true,
	"useroad": true, "volleyoff": true, "volleyon": true, "walk": true,
	"weather": true, "wheeldest": true, "wheeldir": true, "wheelleft": true,
	"wheelleftbck": true, "wheelleftfwd": true, "wheelright": true, "wheelrightbck": true,
	"wheelrightfwd": true, "wheelspec": true, "winbattle": true, "zoom": true,
}
